pipeline {
  agent none
    stages {
        stage('Build') {
            agent {
            docker {
                image 'maven:3.6.3-jdk-8-alpine'
            }
            }
            steps {
            sh 'mvn --version'
            }
        }
        stage('Deploy') {
            agent {
            docker {
                image 'node:16-alpine'
            }
            }
            steps {
            sh 'node --version'
            }
        }
        }
     }
