pipeline {
  agent none
    stages {
        stage('Build') {
            agent {
            docker {
                image 'maven:3.8.6-eclipse-temurin-8'
            }
            }
            steps {
            sh 'mvn --version'
            }
        }
        stage('Deploy') {
            agent {
            docker {
                image 'node:16-alpine'
            }
            }
            steps {
            sh 'node --version'
            }
        }
        }
     }
